version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:Fiesta123@postgres:5432/temponest
      - NEXTAUTH_SECRET=your-secret-key-change-this-in-production
      - NEXTAUTH_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - temponest-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Fiesta123
      - POSTGRES_DB=temponest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - temponest-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - temponest-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - temponest-network

volumes:
  postgres_data:
  redis_data:

networks:
  temponest-network:
    driver: bridge